name: Update Theos Submodules

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git submodule update --remote --init --recursive
          git commit --all -m "[submodules] Update submodules to the latest commit" && git push || echo "No changes were made"
